In [31]:
import numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))

b = 0.1
input_nums = np.array([0.5,0.3,0.8]).reshape(-1,1)
print(input_nums)
w_input_hidden1 = np.arange(0.1,1.0,0.1).reshape(3,-1)
print(w_input_hidden1)

hidden1 = sigmoid(np.dot(w_input_hidden1,input_nums) + b)
hidden1 = np.round(hidden1,2)
print(hidden1)

w_hidden1_hidden2 = np.arange(0.2,0.71,0.1).reshape(2,-1)
print(w_hidden1_hidden2)

hidden2 = sigmoid(np.dot(w_hidden1_hidden2,hidden1) + b)
hidden2 = np.round(hidden2,2)
print(hidden2)

w_hidden2_output = np.arange(0.3,0.61,0.1).reshape(2,-1)
print(w_hidden2_output)
output = np.dot(w_hidden2_output,hidden2)+b
print(output)

[[0.5]
 [0.3]
 [0.8]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
[[0.61]
 [0.72]
 [0.8 ]]
[[0.2 0.3 0.4]
 [0.5 0.6 0.7]]
[[0.68]
 [0.8 ]]
[[0.3 0.4]
 [0.5 0.6]]
[[0.624]
 [0.92 ]]


In [ ]:

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_deriv(a):
    return a * (1 - a)

b = 0.1 #편향
lr = 0.1 #학습률

input_nums = np.array([0.5,0.3,0.8]).reshape(-1,1)
y = np.array([1,0]).reshape(-1,1)

w_input_hidden1 = np.arange(0.1,1.0,0.1).reshape(3,-1)
w_hidden1_hidden2 = np.arange(0.2,0.71,0.1).reshape(2,-1)
w_hidden2_output = np.arange(0.3,0.61,0.1).reshape(2,-1)


def forward(step_name):
    global hidden1, hidden2, output
    hidden1 = sigmoid(np.dot(w_input_hidden1, input_nums) + b)
    hidden1 = np.round(hidden1, 2)

    hidden2 = sigmoid(np.dot(w_hidden1_hidden2, hidden1) + b)
    hidden2 = np.round(hidden2, 2)

    output = np.dot(w_hidden2_output, hidden2) + b

    E = np.sum((y - output)**2)
    print(f"--- {step_name} ---")
    print("hidden1 =\n", hidden1)
    print("hidden2 =\n", hidden2)
    print("output  =\n", output)
    print("오차 E   =", round(E, 5))
    print()


def backward(step_name):
    global w_input_hidden1, w_hidden1_hidden2, w_hidden2_output, b

    delta3 = 2 * (output - y)
    delta3 = np.round(delta3,2)

    delta2 = np.dot(w_hidden2_output.T, delta3) * sigmoid_deriv(hidden2)
    delta2 = np.round(delta2,2)

    delta1 = np.dot(w_hidden1_hidden2.T, delta2) * sigmoid_deriv(hidden1)
    delta1 = np.round(delta1,2)

    dW_hidden2_output = np.dot(delta3, hidden2.T)
    dW_hidden1_hidden2 = np.dot(delta2, hidden1.T)
    dW_input_hidden1 = np.dot(delta1, input_nums.T)

    db = np.sum(delta3) + np.sum(delta2) + np.sum(delta1)
    db = np.round(db,2)

    print(f"--- {step_name} ---")
    print("delta3(출력층) =\n", delta3)
    print("delta2(은닉2층) =\n", delta2)
    print("delta1(은닉1층) =\n", delta1)
    print("기울기(h2->출력) =\n", dW_hidden2_output)
    print("기울기(h1->h2) =\n", dW_hidden1_hidden2)
    print("기울기(입력->h1)) =\n", dW_input_hidden1)
    print("db =", db)
    print()


    w_hidden2_output -= lr * dW_hidden2_output
    w_hidden1_hidden2 -= lr * dW_hidden1_hidden2
    w_input_hidden1 -= lr * dW_input_hidden1
    b -= lr * db


forward("순전파 1회차")
backward("역전파 1회차")
forward("순전파 2회차")
backward("역전파 2회차")
forward("순전파 3회차")

--- 순전파 1회차 ---
hidden1 =
 [[0.61]
 [0.72]
 [0.8 ]]
hidden2 =
 [[0.68]
 [0.8 ]]
output  =
 [[0.624]
 [0.92 ]]
오차 E   = 0.98778

--- 역전파 1회차 ---
delta3(출력층) =
 [[-0.75]
 [ 1.84]]
delta2(은닉2층) =
 [[0.15]
 [0.13]]
delta1(은닉1층) =
 [[0.02]
 [0.02]
 [0.02]]
기울기(h2->출력) =
 [[-0.51   -0.6   ]
 [ 1.2512  1.472 ]]
기울기(h1->h2) =
 [[0.0915 0.108  0.12  ]
 [0.0793 0.0936 0.104 ]]
기울기(입력->h1)) =
 [[0.01  0.006 0.016]
 [0.01  0.006 0.016]
 [0.01  0.006 0.016]]
db = 1.43

--- 순전파 2회차 ---
hidden1 =
 [[0.58]
 [0.69]
 [0.78]]
hidden2 =
 [[0.64]
 [0.77]]
output  =
 [[0.53584  ]
 [0.5455792]]
오차 E   = 0.5131

--- 역전파 2회차 ---
delta3(출력층) =
 [[-0.93]
 [ 1.09]]
delta2(은닉2층) =
 [[0.02]
 [0.01]]
delta1(은닉1층) =
 [[0.]
 [0.]
 [0.]]
기울기(h2->출력) =
 [[-0.5952 -0.7161]
 [ 0.6976  0.8393]]
기울기(h1->h2) =
 [[0.0116 0.0138 0.0156]
 [0.0058 0.0069 0.0078]]
기울기(입력->h1)) =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
db = 0.19

--- 순전파 3회차 ---
hidden1 =
 [[0.57]
 [0.68]
 [0.78]]
hidden2 =
 [[0.63]
 [0.76]]
output  =
 [[0.6006512]
